### ISSUE TITLE
RCRUD on RoleTypes

### ISSUE THREAD

**Issue by Jonathon22** [Jonathon22/lll-Emporium#62]
## Feature Summary
GIVEN a user is logged in 
WHEN navigating to profile 
THEN they are given option to choose role type
## Acceptance Criteria
A user that is logged in is given or chose a role type

## Technical Requirements
- [ ] Create a option to choose role type on creation of user

**Comment by Greenfin17** [comment]
CRUD on role types available at users/roletypes
